CheckOutForm/Controllers/DevicesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CheckOutForm.Models;
using CheckOutForm.Models.DataGroups;

namespace CheckOutForm.Controllers
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    public class DevicesController : Controller
    {
        public DateTime TodaysDate { get; private set; } = DateTime.UtcNow;   // Selects todays date based on client location instead of server location

        private readonly CheckOutFormContext _context;
        public DevicesController(CheckOutFormContext context)
        {
            _context = context;
        }

        // Summarize the count of devices in the database
        public async Task<ActionResult> Summary()
        {
            IQueryable<DeviceTypeGroup>
                 data =
                 from device in _context.Devices
                 group device by device.DeviceType into deviceTypeGroup
                 select new DeviceTypeGroup()
                 {
                     DeviceTypes = deviceTypeGroup.Key,
                     DeviceTypesCount = deviceTypeGroup.Count(),
                     RetiredCount = (deviceTypeGroup.Where(dc => dc.Retired == "True")).Count(),
                     AvailableLoaners = (deviceTypeGroup.Where(dc => dc.Assignee == "Loaner")).Count(),

                     ADevices = (deviceTypeGroup.Where(dc => dc.NameTag.Contains("A-") || dc.NameTag.Contains("USAV-Tablet")).Count(),
                     BDevices = (deviceTypeGroup.Where(dc => dc.NameTag.Contains("B-")).Count(),
                     CDevices = (deviceTypeGroup.Where(dc => dc.NameTag.Contains("C-") || dc.NameTag.Contains("Tab") || dc.NameTag.Contains("iPad"))).Count(),
                     DDevices = (deviceTypeGroup.Where(dc => dc.NameTag.Contains("D-"))).Count(),

                     ARetired = (deviceTypeGroup.Where(dc => dc.NameTag.Contains("A-") || dc.NameTag.Contains("A-Tablet") || dc.NameTag.Contains("ITTab") || dc.NameTag.Contains("Projector".Count(),
                     BRetired = (deviceTypeGroup.Where(dc => dc.NameTag.Contains("B-") && dc.Retired == "True")).Count(),
                     CRetired = (deviceTypeGroup.Where(dc => dc.NameTag.Contains("C-") || dc.NameTag.Contains("Tab") || dc.NameTag.Contains("iPad")).Where(b => b.Retired == "True")).Count(),
                     DRetired = (deviceTypeGroup.Where(dc => dc.NameTag.Contains("D-") && dc.Retired == "True")).Count(),
                 };
            return View(await data.AsNoTracking().ToListAsync());
        }

        public async Task<IActionResult> Index(int? devicesID, string sortOrder, string currentFilter, string searchString, int? pageNumber) // Removed  int? deviceSpecsID,
        {
            var viewModel = new DeviceIndexData
            {
                Devices = await _context.Devices
                  .AsNoTracking()
                  .OrderBy(i => i.DevicesID)
                  .ToListAsync()
            };

            if (devicesID != null)
            {
                ViewData["DevicesID"] = devicesID.Value;
                Devices deviceModels = viewModel.Devices.Where(i => i.DevicesID == devicesID.Value).Single();
            }

            ViewData["CurrentSort"] = sortOrder;
            ViewData["DeviceTypeSortParam"] = String.IsNullOrEmpty(sortOrder) ? "type_desc" : "";
            ViewData["NameTagSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AssigneeSortParam"] = String.IsNullOrEmpty(sortOrder) ? "assigne_desc" : "";
            ViewData["DomainSortParam"] = String.IsNullOrEmpty(sortOrder) ? "domain_desc" : "";
            ViewData["EntryDateSortParam"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["BrandSortParam"] = String.IsNullOrEmpty(sortOrder) ? "brand_desc" : "";
            ViewData["ModelSortParam"] = String.IsNullOrEmpty(sortOrder) ? "model_desc" : "";
            ViewData["SerialSortParam"] = String.IsNullOrEmpty(sortOrder) ? "serial_desc" : "";
            ViewData["OSSortParam"] = String.IsNullOrEmpty(sortOrder) ? "os_desc" : "";
            ViewData["CPUSortParam"] = String.IsNullOrEmpty(sortOrder) ? "cpu_desc" : "";
            ViewData["CPUSpeedSortParam"] = String.IsNullOrEmpty(sortOrder) ? "cpuspeed_desc" : "";
            ViewData["RAMSortParam"] = String.IsNullOrEmpty(sortOrder) ? "ram_desc" : "";
            ViewData["HDSizeSortParam"] = String.IsNullOrEmpty(sortOrder) ? "hdsize_desc" : "";
            ViewData["HDTypeSortParam"] = String.IsNullOrEmpty(sortOrder) ? "hdtype_desc" : "";
            ViewData["OpticalSortParam"] = String.IsNullOrEmpty(sortOrder) ? "optical_desc" : "";
            ViewData["ScreenSizeSortParam"] = String.IsNullOrEmpty(sortOrder) ? "screen_desc" : "";
            ViewData["UserSortParam"] = String.IsNullOrEmpty(sortOrder) ? "user_desc" : "";
            ViewData["PasswordSortParam"] = String.IsNullOrEmpty(sortOrder) ? "pwd_desc" : "";
            ViewData["RetiredSortParam"] = String.IsNullOrEmpty(sortOrder) ? "retired_desc" : "";
            ViewData["NotesSortParam"] = String.IsNullOrEmpty(sortOrder) ? "notes_desc" : "";
            ViewData["CurrentFilter"] = searchString;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var devices = from d in _context.Devices
                          select d;
            if (!String.IsNullOrEmpty(searchString))
            {
                devices = devices.Where(s => s.NameTag.Contains(searchString) || s.Assignee.Contains(searchString) || s.EntryDate.ToString().Contains(searchString) || s.DeviceType.Contains(searchString) || s.Notes.Contains(searchString) || s.Model.Contains(searchString));
            }
            devices = sortOrder switch
            {
                "type_desc" => devices.OrderBy(s => s.DeviceType),
                "name_desc" => devices.OrderBy(s => s.NameTag),
                "assigne_desc" => devices.OrderBy(s => s.Assignee),
                "domain_desc" => devices.OrderBy(s => s.Domain),
                "Date" => devices.OrderBy(s => s.EntryDate),
                "date_desc" => devices.OrderBy(s => s.EntryDate),
                "brand_desc" => devices.OrderBy(s => s.Brand),
                "model_desc" => devices.OrderBy(s => s.Model),
                "serial_desc" => devices.OrderBy(s => s.Serial),
                "os_desc" => devices.OrderBy(s => s.OS),
                "cpu_desc" => devices.OrderBy(s => s.CPU),
                "cpuspeed_desc" => devices.OrderBy(s => s.ProcessorSpeed),
                "ram_desc" => devices.OrderBy(s => s.RAM),
                "hdsize_desc" => devices.OrderBy(s => s.DriveSize),
                "hdtype_desc" => devices.OrderBy(s => s.HardDriveType),
                "optical_desc" => devices.OrderBy(s => s.Optical),
                "screen_desc" => devices.OrderBy(s => s.ScreenSize),
                "user_desc" => devices.OrderBy(s => s.User),
                "pwd_desc" => devices.OrderBy(s => s.Pwd),
                "retired_desc" => devices.OrderBy(s => s.Retired),
                "notes_desc" => devices.OrderBy(s => s.Notes),
                _ => devices.OrderBy(s => s.DevicesID),
            };
            int pageSize = 10;
            return View(await PaginatedList<Devices>.CreateAsync(devices.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Devices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var devices = await _context.Devices
                .FirstOrDefaultAsync(m => m.DevicesID == id);
            if (devices == null)
            {
                return NotFound();
            }

            return View(devices);
        }

        // GET: Devices/Create
        public IActionResult Create()
        {
            return View(new Devices
            {
                DeviceType = "Laptop",
                NameTag = "A-",
                Assignee = "User",
                Brand = "Lenovo",
                Model = "Yoga 720-13IKB 81CS",
                Serial = "S/N:",
                OS = "Windows 10 Pro x64",
                CPU = "Intel i5-8250U",
                ProcessorSpeed = "1.6GHz",
                RAM = "8GB",
                DriveSize = "250GB",
                HardDriveType = "SSD",
                Optical = "No",
                ScreenSize = 13,
                User = "tobor",
                Pwd = "I_Am_God@legion",
                Domain = "osbornepro.com",
                EntryDate = TodaysDate,
                Retired = "False",
                Notes = "None"
            }
                );
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DeviceType,NameTag,Assignee,Domain,EntryDate,Brand,Model,Serial,OS,CPU,ProcessorSpeed,RAM,DriveSize,HardDriveType,Optical,ScreenSize,User,Pwd,Retired,Notes")] Devices devices) // removed , string[] selectedDeviceSpecs from the end
        {
            if (ModelState.IsValid)
            {
                _context.Add(devices);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(devices);
        }

        // GET: Devices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var devices = await _context.Devices
                .AsNoTracking()

CheckOutForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OsbornePro </title>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background: url('@Url.Content("~/images/backgroundimage.png")')">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a href="@Url.Action("Index", "core")" class="navbar-brand">
                    <img src="~/images/logobanner.png" alt="Check Out Forms" height="30" width="130" asp-area="" asp-page="/Index">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="LaptopPolicy">Laptop Policy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Devices" asp-action="Index">Devices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Rentals" asp-action="Index">Rentals</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark navbar-dark text-muted">
        <div class="container">
            &copy; 2019 - OsbornePro - <a asp-area="" asp-controller="Home" asp-action="LaptopPolicy">Laptop Policy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>